# MATH 210 Introduction to Mathematical Computing

## March 8, 2016

1. Linear algebra
    * Determinants
    * Eigenvalues
    * Eigenvectors
    * Inverses

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import scipy.linalg as la

## 1. Linear algebra with SciPy

Let's create a random matrix and recall @ is martix multiplication.

In [2]:
M = np.random.randint(0,10,[3,3])
M

array([[2, 3, 3],
       [6, 8, 5],
       [9, 7, 1]])

In [3]:
M@M

array([[ 49,  51,  24],
       [105, 117,  63],
       [ 69,  90,  63]])

We can take the transpose with `.T` method:

In [4]:
M.T

array([[2, 6, 9],
       [3, 8, 7],
       [3, 5, 1]])

Notice that $M M^T$ is a symmetric matrix

In [6]:
M@M.T

array([[ 22,  51,  42],
       [ 51, 125, 115],
       [ 42, 115, 131]])

We can find the inverse using `scipy.linalg.inv`:

In [7]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [8]:
la.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

We find the determinant using `scipy.linalg.det`:

In [9]:
la.det(A)

-2.0

We can find the trace of a matrix:

In [10]:
np.trace(A)

5

### Example: Characteristic ploynomials and Cayley-Hamilton Theorem

The characteristic ploynomial of a 2x2 square matrix A is

$$
p_A(\lambda) = \lambda^2 - \mathrm{tr(A)}\lambda + det(A)
$$

The Cayley-Hamilton Theorem says that a square matrix satisfies its characteristic polynomial:

$$
p_A(A) = A^2 - \mathrm{tr(A)}A + det(A)I = 0
$$

Let's verify this theorem for a few different matricies:

In [11]:
A

array([[1, 2],
       [3, 4]])

In [13]:
trace_A = np.trace(A)
det_A = la.det(A)
I = np.eye(2)

In [14]:
A@A - trace_A*A + det_A*I

array([[ 0.,  0.],
       [ 0.,  0.]])

Let's do this again for some randoms:

In [36]:
B = np.random.randint(0,10,[2,2])
B

array([[4, 9],
       [7, 0]])

In [37]:
trace_B = np.trace(B)
det_B = la.det(B)
I = np.eye(2)
B@B - trace_B*B + det_B*I

array([[ 0.,  0.],
       [ 0.,  0.]])

### Example: Eigenvalues, Eigenvectors and Symmetric Matricies

The eigenvalues of a symmetric matrix are always real and the eigenvectors are always orthogonal.

In [25]:
n = 4
P = np.random.randint(0,10,[n,n])
P

array([[1, 7, 3, 5],
       [1, 5, 4, 5],
       [2, 6, 3, 0],
       [2, 7, 6, 8]])

In [27]:
S = P@P.T # This is a symmetric matrix
S

array([[ 84,  73,  53, 109],
       [ 73,  67,  44, 101],
       [ 53,  44,  49,  64],
       [109, 101,  64, 153]])

We can find the eigenvectors and eigenvalues using `scipy.linalg.eig`:

In [29]:
evals, evecs = la.eig(S)

In [30]:
evals

array([  3.30877741e+02+0.j,   1.92701685e+01+0.j,   2.75154352e+00+0.j,
         1.00547003e-01+0.j])

In [31]:
evecs

array([[-0.4972152 , -0.09646818,  0.85663068,  0.09825894],
       [-0.44770622,  0.16863459, -0.14146211, -0.86666602],
       [-0.31609222, -0.90292405, -0.28914226,  0.03479414],
       [-0.67262315,  0.38338549, -0.4031986 ,  0.4878776 ]])

In [33]:
v1 = evecs[:,0] # First column
v1

array([-0.4972152 , -0.44770622, -0.31609222, -0.67262315])

In [34]:
v2 = evecs[:,1] # Second column
v2

array([-0.09646818,  0.16863459, -0.90292405,  0.38338549])

In [35]:
v1@v2

-5.5511151231257827e-17

The dot product of eigenvectors $v1$ and $v2$ is zero so they are orthogonal!