# MATH 210 Introduction to Mathematical Computing

## March 10, 2017

1. More linear algebra
    * Matrix powers
    * Eigenvalues
    * Eigenvactors
2. Examples
    * Projections
    * Least squares regression 3

In [2]:
import numpy as np
import scipy.linalg as la
import matplotlib.pyplot as plt
%matplotlib inline

## 1. More linear algebra

We've already seen matrix multiplication of numpy arrays using the @ operator:

In [4]:
M = np.array([[2,1],[-2,5]])
M

array([[ 2,  1],
       [-2,  5]])

In [5]:
M@M

array([[  2,   7],
       [-14,  23]])

Remember that `M**2` is an array operation on Numpy arrays and computes the squares of each element:

In [6]:
M**2

array([[ 4,  1],
       [ 4, 25]])

What if we want to comput higher powers of M (as matrix multiplication)
like $M^3=MMM$?

We need to use the function `numpy.linalg.matrix_power`:

In [7]:
np.linalg.matrix_power(M,2)

array([[  2,   7],
       [-14,  23]])

In [8]:
np.linalg.matrix_power(M,3)

array([[-10,  37],
       [-74, 101]])

In [11]:
from numpy.linalg import matrix_power as mpow

In [13]:
mpow(M,5)

array([[ -538,   781],
       [-1562,  1805]])

### Example: Use diagonalization to compute matrix powers

If $M$ is an $nxn$ matrix with $n$ real eigenvalues and $n$ distinct eigenvectors, then we can diagonalize M as $M = PDP^{-1}$ where the columns of P are the (unit) eigenvectors of M and D has corresponding eigenvalues along the diagonal.

Use this to constuct a matrix with given eigenvalues $\lambda_1 = 3$ and $\lambda_2 = 1$ and eigenvectors $v_1 = [1,1]^T$ and $v_2 = [1,-1]^T$.

In [14]:
P = np.array([[1,1],[1,-1]])
P

array([[ 1,  1],
       [ 1, -1]])

In [15]:
D = np.diag((3,1))
D

array([[3, 0],
       [0, 1]])

In [16]:
M = P@D@la.inv(P)
M

array([[ 2.,  1.],
       [ 1.,  2.]])

In [18]:
evals,evecs = la.eig(M)

In [19]:
evals

array([ 3.+0.j,  1.+0.j])

In [20]:
evecs

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

Let's compute high powers of M in two ways: (1) just by computing $M^k = MMM\dots$ by matrix muliplication, (2) by $M = PDP^{-1}$ and $M^k = PD^kP^{-1}$.

In [28]:
Pinv = la.inv(P)

In [37]:
k = 20

In [38]:
%timeit mpow(M,k)

The slowest run took 77.14 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 25.4 µs per loop


In [39]:
%timeit P @ D**k @ Pinv

The slowest run took 17.96 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 9.35 µs per loop


## 2. Examples

### Projections

The formula to project a vector v onto a vector w is:

$$
\mathrm{proj}_w(v) = \frac{v \cdot w}{w \cdot w} w
$$

Let's create a function called proj which computes the projection of v onto w.

In [54]:
def proj(v,w):
    """Project vector v onto w."""
    v = np.array(v)
    w = np.array(w)
    return np.sum(v*w)/np.sum(w*w) * w # or (v@w)/(w@w) * w

In [53]:
proj([1,2],[1,2])

array([ 1.,  2.])

In [55]:
proj([1,2,3],[1,1,1])

array([ 2.,  2.,  2.])

### About 1D and 2D NumPy arrays and the @ operator

Notice that the @ operator computes the dot product of 1D NumPy arrays. 

In [56]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [57]:
x.shape

(3,)

In [59]:
x.ndim

1

In [60]:
x@x

14

In [62]:
x.reshape(3,1)@x.reshape(1,3)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [64]:
y.ndim

2

In [65]:
y.shape

(1, 3)

In [63]:
y = x.reshape(1,3)
y

array([[1, 2, 3]])

In [66]:
x

array([1, 2, 3])